---
configuration:
  agency_code: 
  project_code: uatci
  cidr_ingress_egress_zone_subnet_ingress_internet: 100.73.38.0/26
  cidr_ingress_egress_zone_subnet_ingress_agw_internet: 100.73.38.64/26
  cidr_ingress_egress_zone_subnet_egress_internet: 100.73.39.0/26
  cidr_ingress_egress_zone_subnet_egress_mgmt_internet: 100.73.39.64/26
  cidr_ingress_egress_zone_subnet_ingress_intranet: 10.210.118.128/26
  cidr_ingress_egress_zone_subnet_ingress_agw_intranet: 10.210.118.192/27
  cidr_ingress_egress_zone_subnet_egress_intranet: 10.210.119.0/26
  cidr_ingress_egress_zone_subnet_egress_mgmt_intranet: 10.210.119.64/26
  cidr_internet_zone_subnet_app:  # dummy value
  cidr_internet_zone_subnet_data:  # dummy value
  cidr_management_zone_subnet_infra: 100.73.40.0/26
  cidr_management_zone_subnet_security: 100.73.40.64/26
  cidr_management_zone_subnet_bastion: 100.73.40.128/26
  cidr_devops_zone_subnet_runner: 100.73.33.0/28
  cidr_devops_zone_subnet_gateway: 100.73.33.16/28
# solution_accelerators - value is "1" or "0" : 1 = yes, 0 = no     
solution_accelerators:
  ingress_egress_zone:
    firewall: 1 
    agw: 1 
    firewall_egress: 1 
  ingress_egress_zone_intranet:
    firewall: 1 
    agw: 1 
    firewall_egress: 1 
  internet_zone: 
    app: 
      app_aks: 0
      app_acr: 0    
    data: 
      data_cosmosdb: 0   
      data_mssql: 0   
      data_storage_account: 0       
  management_zone: 
    bastion: 1
    tooling_server: 1             
    monitoring: 1    
    recovery_services_vault: 1 
    ampls: 1   
    application_insights: 0 # wip
    automation: 0          # wip           
  devops_zone: 
    vm_runner: 1
                   
               
           
