---
configuration_application:
  on_prem_api_ip: 10.0.0.5 # dummy value
  on_prem_sftp_ip: 10.0.0.6 # dummy value
  on_prem_mq_ip: 10.0.0.7 # dummy value
  ingress_intranet_agw_ip: 10.210.118.202 # dummy value
  ingress_internet_agw_ip: 100.73.38.74 # dummy value   
  ingress_internet_aks_ip: 100.2.0.95 # dummy value
  ingress_intranet_aks_ip: 100.2.0.95 # dummy value
  ingress_internet_aks_fqdn: aks-moris # dummy value  
  ingress_intranet_aks_fqdn: aks-moris # dummy value    
  ingress_internet_agw_fqdn: moris # dummy value demoapp1.internet.caflabs.com 
  ingress_intranet_agw_fqdn: moris # dummy value demoapp1.intranet.caflabs.com    
  ingress_internet_dns_zone: internet.gra.gov.sg # dummy value demoapp1.internet.caflabs.com 
  ingress_intranet_dns_zone: gra.gov.sg # dummy value demoapp1.intranet.caflabs.com    
  egress_intranet_firewall_ip: 10.210.119.4 # dummy value intranet firewall subnet cidr + 4     
  egress_internet_firewall_ip: 100.73.39.4 # dummy value internet firewall subnet cidr + 4    
  # ingress_intranet_domain: caflabs.com # dummy value     
  # ingress_internet_domain: caflabs.com # dummy value     
 



                   
               
           
